Kapeli/Dash-User-Contributions

docsets/Haiku_Book/Haiku_Book.tgz.txt, docsets/Haiku_Book/README.md, docsets/Haiku_Book/docset.json
API changes to:
BInvoker, BMessage, BMessageRunner, BJoyStick, BSize, BToolTip,
BTab,BTabView, BOptionPopUp and BTextControl
=> Haiku docset update 0.4.8

docsets/Theano/README.md
Hi,
I'm a contributor of Theano, I made this PR to improve the existing docset.
I have asked Aziz, he generate the doc from our website, however we prefer to use the doc generated from our dev repo, we think this version would be more useful. It's still 0.6 version, but somewhere ahead of the website version.
PS: do I need to delete the .tgz.txt file?
=> Improve Theano docset

docsets/Docker/README.md, docsets/Docker/docset.json
=> Fixed protocol-relative links and updated version to 1.4.1/1

docsets/React/docset.json
Fixes https://github.com/chenglou/react-dash/issues/2
=> Bump React to 0.12.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
New version of the docs already, sheesh ;)
=> Updated Vaadin with 7.4.0

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Hullo, Kapeli-- Got another Vaadin docset update for you here...
=> Updated Vaadin with 7.4.1

docsets/Haiku_Book/Haiku_Book.tgz.txt, docsets/Haiku_Book/README.md, docsets/Haiku_Book/docset.json
Changes to ScrollView and BReferencable classes
=> Haiku docset update

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another version update... thanks!
=> Update Vaadin to version 7.4.2

docsets/React/docset.json
Fixes #388 
Fixes https://github.com/chenglou/react-dash/issues/3
=> Bump React to 0.13.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Here's a cleaner history (single-commit) pull request for the Vaadin 7.4.3 docset.
=> new Vaadin version 7.4.3, docset index fixed

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Here's yet another minor-version docset update...
=> new Vaadin version 7.4.4

docsets/Docker/docset.json
Added v1.6.0 of Docker docs, including section TOCs. 
Question: How would I get these docs added to the list of docs available to the Dash iOS app?
Thanks!
=> Added v1.6.0 of Docker docs

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Another minor version update. (And I get to fix a spelling mistake in my README.) Thanks!
=> new Vaadin version 7.4.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> new Vaadin version 7.4.6

docsets/Ionic/docset.json
Is it possible to test docsets locally via your travis verification script?
=> ionic: Give it a new try.

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another minor version update. Thanks!
=> new Vaadin version 7.4.7

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another minor-version update.
=> new Vaadin version 7.4.8

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.5.0

docsets/ClojureScript/docset.json
- add markdown-formatted descriptions (not all yet)
- add usage examples (not all yet)
- add "see also" symbols (not all yet)
- reformat syntax pages with usage sections
- add external docs links
- replace pseudo-namespaces and pseudo-symbols with conceptual names to
reduce confusion
=> add supplementary docs to ClojureScript

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
A terrible rhyming haiku just for you:
A minor update
For my lil' Vaadin template
Dash 3 is so great
=> Update Vaadin to version 7.5.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Another minor-version doc update.
=> Update Vaadin to version 7.5.2

docsets/Kotlin/docset.json
=> Update Kotlin docset to 0.12.613. Add API docs

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.5.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.5.4

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another minor version update -- thanks!
=> Update Vaadin to version 7.5.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.5.6

docsets/Bullet/Makefile
=> Set DashDocSetKeyword to bullet in Info.plist

docsets/Bullet/Makefile, docsets/Bullet/docset.json
This is the latest Bullet release.
=> Add Bullet 2.83.6

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.5.7

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another minor-version update.
=> Update Vaadin to version 7.5.8

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Let me know if you'd prefer I clear out the previous patch version (e.g. remove 7.5.8 when adding 7.5.9).
Thanks!
=> Update Vaadin to version 7.5.9

docsets/Bokeh/Bokeh.tgz.txt, docsets/Bokeh/docset.json
The current Bokeh docset (0.8.2) is outdated.
=> Upgrade to Bokeh 0.10.0

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.5.10

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.6.0

docsets/Bokeh/Bokeh.tgz.txt, docsets/Bokeh/README.md, docsets/Bokeh/docset.json
I modified the stock release so that the external stylesheet was embedded and the version number was hardcoded (instead of using the internal library version).
=> Upgrade to Bokeh 0.11.0

docsets/Eigen/Eigen.tgz.txt, docsets/Eigen/README.md, docsets/Eigen/docset.json
Updated the Info.plist file in both versions to have "eigen" as the dash keyword.
Updated the README.md and docset.json to reflect the version update.
NOTE: The binary in the Eigen directory is the same as what's in versions/3.2.7/
=> Added docs for Eigen version 3.2.7

docsets/Pythonista/docset.json, docsets/tldr/tldr_pages.tgz.txt
This time with the correct locations set in docset.json. :smiley:
=> Updated Pythonista docset to 2.0

docsets/Haiku_Book/Haiku_Book.tgz.txt, docsets/Haiku_Book/docset.json
Haiku Book docset update to 0.5 due to hrev50000.
=> Updated docset to 0.5 prior to hrev50000

docsets/Theano/README.md, docsets/Theano/Theano.tgz.txt, docsets/Theano/docset.json
I have boosted Theano version from 0.6 to 0.7.
=> Update Theano version from 0.6 to 0.7

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.6.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Updated as requested, looks like bad timing on the previous pull request.
=> Update Vaadin to version 7.6.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.6.3

docsets/React_Native/React_Native.tgz.txt, docsets/React_Native/docset.json
=> Update to React-Native v0.21.0

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.6.4

docsets/RxJava/.gitignore, docsets/RxJava/README.md, docsets/RxJava/docset.json, docsets/RxJava/offline-images/.gitignore, docsets/RxJava/offline-images/index.js, docsets/RxJava/offline-images/package.json
Generate from its official javadoc, with all external images off-lined to improve performance.
=> Added docset of RxJava 1.1.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.6.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another minor version update...
=> Update Vaadin to version 7.6.6

docsets/Cinder/Cinder.tgz.txt, docsets/Cinder/docset.json
Hi there, finally got around to updating the Cinder docset for the latest Cinder. Thanks again for the great app!
=> Cinder docset update

docsets/Astropy/README.md, docsets/Astropy/docset.json
These haven't been updated in a while, so I took the liberty of trying it myself.  The original author @iamaziz pulled the html docs from readthedocs and then ran doc2dash on them.  But I couldn't get that to work, so I built the docs from the source repo instead.
=> Update astropy docset to v1.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.6.7

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.6.8

docsets/React_Native/React_Native.tgz.txt, docsets/React_Native/docset.json
Removed all previous releases from build, reducing the docset size by 95%!
=> Update to React-Native v0.30.0

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.7.0

docsets/Seaborn/README.md, docsets/Seaborn/Seaborn.tgz.txt, docsets/Seaborn/docset.json
Updates for Seaborn (the matplotlib one)
Fixes:
- Guides were previously a mess, with duplicate entries and non-useful titles. Now strictly follows the "tutorials" page the Seaborn documentation comes with.
Adds:
- Samples - I've added everything in the "examples gallery" as a sample, with names for what they are. 
- Classes and Functions are now all properly listed in Dash.
=> Update to Seaborn 0.7.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.7.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.7.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Seems like we just did this yesterday. Oh wait, we did! Another minor version out today.
=> Update Vaadin to version 7.7.3

docsets/ns-3/Info.plist, docsets/ns-3/docset.json
I updated my docset to the newest version.
=> Updated ns-3 to 3.26

docsets/TensorFlow/TensorFlow.tgz.txt, docsets/TensorFlow/docset.json
Do I need to include the old versions?
=> Update TensorFlow to 0.11

docsets/FFmpeg/docset.json, docsets/Libav/docset.json
finally I've made the section names correct now, sorry for another PR.
=> updated libav/ffmpeg docset with correct section names

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.7.4

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another minor version update, hard on the heels of the last one.
=> Update Vaadin to version 7.7.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.7.6

docsets/Astropy/README.md, docsets/Astropy/docset.json
=> Update Astropy to v1.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 7.7.7

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Incremental version update. Also adds icons for docset.
=> Updating boto3 docset to version 1.4.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.0.0

docsets/RxJava/docset.json
@Kapeli I fixed your comments. Considering the original dev has gone berserk, I am willing to maintain these docsets for the time being. Hope it's good enough now.
=> Now with all versions

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.0.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.0.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.0.3

docsets/PyTorch/docset.json
- Correct html Latex rendering.
- Correct link to index page.
=> Update PyTorch 0.1.10 to 0.1.11 and Fix

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.0.5

docsets/Kotlin/docset.json
Hey Bogdan,
haven't updated this in a while. So here we go. 😃
Have a great day,
Marcel
=> Kotlin 1.1 update

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.0.6

docsets/Editorial/docset.json, docsets/Pythonista/docset.json
If needed to be manually updated, here is the tarball of the Pythonista docset: https://app.box.com/s/eq1e0dsv9teub6jwssemwik6o7o59kyv
And the Editorial docset:
https://app.box.com/s/pbmwrm6nb48nohqwxwq154gt8auqmyse
=> Updated Pythonista docset to 3.1

docsets/Boto3/README.md, docsets/Boto3/docset.json
Incremental update that adds documentation for a few new classes and corrects typos.
=> Updating Boto3 to version 1.4.4

docsets/FFmpeg/docset.json, docsets/FFmpeg/versions/3.0.3/FFmpeg.tgz.txt, docsets/FFmpeg/versions/3.0.4/FFmpeg.tgz.txt, docsets/FFmpeg/versions/3.1.4/FFmpeg.tgz.txt, docsets/FFmpeg/versions/3.1.5/FFmpeg.tgz.txt, docsets/FFmpeg/versions/3.2/FFmpeg.tgz.txt, docsets/Libav/docset.json, docsets/Libav/versions/11.8/Libav.tgz.txt, docsets/Libav/versions/12/Libav.tgz.txt, docsets/Libav/versions/9.20/Libav.tgz.txt
this will update ffmpeg 3.x to newest version, 
also update libav 12.1/11.8.
Hope this passes tests.
=> update ffmpeg/libav docsets to newest version.

docsets/cvxpy/README.md
add the python marker to code block for proper highlighting
=> Update cvxpy README

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Another minor version update.
(Annoyingly, my text editor replaced the tabs with spaces due to settings from another project I was working on.)
=> Update Vaadin to version 8.0.7

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.1.2

docsets/Scikit/docset.json
=> update scikit-learn docset to 0.19

docsets/Seaborn/docset.json
=> update Seaborn docset to v0.8

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.1.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.1.4

docsets/CQL/README.md, docsets/CQL/docset.json, docsets/Cassandra/README.md, docsets/Cassandra/docset.json
Add Cassandra and CQL docsets.
=> Add Cassandra and CQL docsets.

docsets/JUCE/docset.json
=> juce-5.1.2

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Pretty routine update. As always, please let me know if I screwed something up and forgot to anything the proper way. Thanks!
=> Updating boto3 doces to version 1.4.7

docsets/Terraform/Terraform.tgz.txt, docsets/Terraform/docset.json
Updated Terraform docset to version 0.10.8
=> updated docset to 0.10.8

docsets/Wagtail/docset.json
=> Update Wagtail docs to 1.13

docsets/FFmpeg/docset.json, docsets/Libav/docset.json
=> add ffmpeg 3.4 docs and bump libav  to 12.2

docsets/Terraform/Terraform.tgz.txt, docsets/Terraform/docset.json
build 0.11.1
Signed-off-by: nicholasjackson <jackson.nic@gmail.com>
=> Created new version of Terraform docs based on the latest terraform

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Documentation updates from dp11
=> V1.3 Updated to LC9 dp11

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Seems a documentation convention has changed as noted in README
=> Updated capture for widget and library summaries

docsets/ns-3/ns-3.tgz.txt
I found a that my docset downloaded through Dash is still the old one. Maybe I messed something up and accidentally added the old instead of the new docset?! 
However, I updated my branch to fix this.
=> Fixed the ns-3 docset, since it still seemed to be the old.

docsets/Terraform/Terraform.tgz.txt, docsets/Terraform/docset.json
=> Update Terraform 0.11.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Version bump. (Missed a few since my notifications about Vaadin updates stopped!)
=> Update Vaadin to version 8.3.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.3.2

docsets/ns-3/Info.plist, docsets/ns-3/docset.json, docsets/ns-3/ns-3.tgz.txt
I updated the ns-3 docset for the recently released version 3.28.
=> Update to ns 3.28

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.3.3

docsets/LiveCode/docset.json
Set now is at LC 9 Stable.
Minor dictionary updates.
Updated release notes.
=> Set now at 9.0 release.

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.4.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.4.2

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Introduces a number of new methods, fixes and service integrations:
https://github.com/boto/boto3/blob/develop/CHANGELOG.rst
=> Update boto3 docset to version 1.7.31

docsets/Powershell/Powershell.tgz.txt, docsets/Powershell/docset.json, docsets/Powershell/versions/3.0/Powershell.tgz.txt, docsets/Powershell/versions/4.0/Powershell.tgz.txt, docsets/Powershell/versions/5.0/Powershell.tgz.txt, docsets/Powershell/versions/5.1/Powershell.tgz.txt, docsets/Powershell/versions/6/Powershell.tgz.txt
Powershell docset now package windows 10 powershell modules (
appx, hyper-v, smbshare, etc.) documentation.
=> Update powershell docset to v0.6

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.4.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.4.4

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Additionally updating the README to provide better instructions
for managing updates.
=> Updating boto3 Docset to v1.7.52

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.4.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.5.0

docsets/PyTorch/docset.json, docsets/pymatgen/docset.json
Update pymatgen doc to v2018.8.7
=> Update pymatgen doc to v2018.8.7

docsets/Elektra/docset.json
👋 Hi,
this pull request adds a DocSet for [Elektra](https://www.libelektra.org) `0.8.24`. If I should change anything in the commit, then please just comment below. Thank you.
Kind regards,
René
=> Add DocSet for Elektra 0.8.24

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Inclusion of widgets guide files and updated to 9.01 release.
=> 9.01 release with guides to widgets.

docsets/LiveCode/README.md, docsets/LiveCode/docset.json, docsets/LiveCode/versions/1.0.0/LiveCode.tgz.txt, docsets/LiveCode/versions/1.0.1/LiveCode.tgz.txt, docsets/LiveCode/versions/1.1/LiveCode.tgz.txt, docsets/LiveCode/versions/1.2/LiveCode.tgz.txt, docsets/LiveCode/versions/1.3/LiveCode.tgz.txt, docsets/LiveCode/versions/1.4.1/LiveCode.tgz.txt, docsets/LiveCode/versions/1.4.2/LiveCode.tgz.txt, docsets/LiveCode/versions/1.4/LiveCode.tgz.txt, docsets/LiveCode/versions/1.5.1/LiveCode.tgz.txt, docsets/LiveCode/versions/1.5/LiveCode.tgz.txt
Dictionary additions:
androidHasPermission (function), androidPermissionExists (function), androidRequestPermission (command), audioPan (property), leftBalance (property), messageDigest (function), rightBalance (property)
Older versions (pre 1.6) have been removed.
=> Dictionary additions and cleanup old versions

docsets/pymatgen/docset.json
=> Update pymatgen docs to v2018.9.30

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Based on LC 9.01 Stable - syntax coloring and links for associations.
=> Description of changes

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Adjust layout of the examples to be more concise and follow existing indentation.
Color syntax elements.
Links to associations.
=> Syntax coloring and layout of examples (corrected), "Associations" links

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Finally got all "Associations" links working.
=> Complete Associations Links

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.6.0

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
9.02rc1 has added significant updates to the dictionary.
=> Docs update with LC9.02rc1

docsets/Elektra/docset.json
👋 Hi,
this pull request adds a DocSet for the most recent version of [Elektra](https://www.libelektra.org). If I should change anything in this PR, then please just comment below. Thank you.
=> Add DocSet for Elektra 0.8.25

docsets/TCLAP/README.md, docsets/TCLAP/docset.json
Trying again with a slightly modified Plist (added isDashDocset)
=> Add TCLAP 1.2.2

docsets/Elm/README.md, docsets/Elm/docset.json
Just a routine update. I generated this with a [patched version](https://github.com/pdamoc/elm-docset/pull/18) of elm-docset that uses the latest version for packages.
=> Update Elm packages

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.6.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.6.4

docsets/Scikit/build.sh, docsets/Scikit/docset.json
Fixing problems with filename case (thanks to @thomasjpfan).
=> Scikit learn 0.20.2

docsets/React_Native/docset.json
Relates to issue #1858, albeit two minor versions later.
=> update react native to version 0.57.0

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Docs updated to those released with LC 9.02 Stable.
=> Updated to 9.02 Stable

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Plus a minor tweak to the README since I keep forgetting about that step.
=> Updating boto3 docset to version 1.9.86

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.7.0

docsets/openFrameworks/README.md, docsets/openFrameworks/docset.json, docsets/openFrameworks/openFrameworks.tgz.txt
if have any issue, let me know.
thanks.
=> openFrameworks 0.10.1 added

docsets/pymatgen/docset.json
Updated pymatgen docset for v2019.2.4.
=> Updated pymatgen docset for v2019.2.4.

docsets/Elektra/docset.json
This pull request updates the main version of the Elektra DocSet (See also: https://github.com/Kapeli/Dash-User-Contributions/pull/2265#issuecomment-467776956).
=> Fix Version Number of Elektra DocSet

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Updating Boto3 docset to version 1.9.106

docsets/TensorFlow/docset.json
=> Update TensorFlow 1.13.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.7.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.7.2

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
LC 9.04 Stable just released.
Dictionary changes included.
Syntax coloring preserved.
=> updated for LC 9.04

docsets/Laravel_Zero/README.md, docsets/Laravel_Zero/docset.json, docsets/Laravel_Zero/versions/2.2.0/laravel-zero.tgz.txt
=> Remove wrong version of Laravel Zero

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.8.2

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Several new methods for recently released services.
=> Updating Boto3 docset to version 1.9.169

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.8.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.8.5

docsets/LifterLMS/docset.json
Added LifterLMS Docset for version 3.33.2
=> LifterLMS Version 3.33.2

docsets/Consul/docset.json, docsets/Vault/docset.json
=> Update Consul and Vault

docsets/Terraform/docset.json, docsets/Vault/docset.json
=> Update Terraform and Vault

docsets/Elektra/docset.json
👋 Hi Bodgan,
this pull request contains the latest DocSet for [Elektra](https://www.libelektra.org). If I should change anything in this PR, then please just comment below. Thank you.
Kind regards,
René
=> Add DocSet for Elektra 0.9

docsets/LifterLMS/docset.json
=> LifterLMS Version  3.34.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.8.6

docsets/pymatgen/docset.json
Update docset to v2019.8.23 version of pymatgen.
=> v2019.8.23

docsets/Python_zh_cn/README.md, docsets/Python_zh_cn/docset.json
add python chinese API document, include python2.7.16 and python3.7.4
=> add Python_zh_cn

docsets/Symfony_Docs/README.md, docsets/Symfony_Docs/docset.json
Adds Symfony documentation guides from https://symfony.com/doc for all supported Symfony versions.
=> Added Symfony Docs https://symfony.com/doc

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.9.0

docsets/Consul/docset.json, docsets/Vault/docset.json
Consul:
- 1.6.1
Vault:
- 1.2.3
=> Update Consul & Vault

docsets/XMake/versions/2.2.8/README.md
=> XMake fixed only

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.9.1

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Significant additions/mods to dictionary.
Syntax colouring finally back.
=> Disctionart updates from 9.5.1rc1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.9.2

docsets/Elektra/docset.json
👋 Hi,
this pull request updates the DocSet for [Elektra](https://www.libelektra.org). If I should change anything, then please just comment below. Thank you.
=> Add DocSet for Elektra 0.9.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.9.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.9.4

docsets/RxJava/docset.json, docsets/RxJava/offline-images/package-lock.json
Updates RxJava docs to 2.2.16.
I tried to follow the directions from [here](https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset), but kinda started to get unclear at the _Copy your docset archive_ step. It doesn't mention copy from where to where so I kinda just guessed based off previous PRs for this docset. Let me know if there needs to be any changes made in order for this to get merged.
=> Update RxJava to 2.2.16

docsets/Elm/Elm.tgz.txt, docsets/Elm/README.md, docsets/Elm/docset.json, docsets/Elm/versions/0.18.0/Elm.tgz.txt
Hi,
this is just an update of 0.19 Elm packages documentation, 0.18 stays the same
=> Update of Elm 0.19 packages documentation on 2020-01-10

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Updating Boto3 docset to version 1.11.9

docsets/Scikit-image/README.md, docsets/Scikit-image/docset.json
I also changed instructions in README as the original one didn't work
for me.
=> Scikit-image updated to 0.16.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.10.0

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.10.1

docsets/Nomad/docset.json
Add Nomad 0.10.3 and 0.10.4 documentation versions.
=> Update Nomad docs

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.10.2

docsets/Consul/docset.json, docsets/Terraform/docset.json, docsets/Vault/docset.json
Consul:
- 1.6.4
- 1.7.1
Terraform:
- 0.12.23
Vault:
- 1.3.3
=> Update Consul, Terraform, Vault

docsets/Kotlin/README.md, docsets/Kotlin/docset.json, docsets/Kotlin/kotlin.tgz.txt
Since @kevincianfarini hasn't kept it up.
=> Kotlin 1.3.70 docset

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Updating Boto3 docset to version 1.12.28

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.10.3

docsets/Elm/Elm.tgz.txt, docsets/Elm/README.md, docsets/Elm/docset.json
This version adds some new packages and fixes missing functions in elm-ui package (and maybe some others as well....
Thank you @alexkorban for noticing ;)
=> Fixed version of Elm packages

docsets/Terraform/README.md
Updated some system requirements after trying to recently build the Terraform docsets on my Ubuntu machine.
=> Updates system requirements for build process of Terraform docset

docsets/Wagtail/docset.json
Hi there,
I just wanted to add Wagtail doc v2.8.1
=> Add Wagtail 2.8.1

docsets/MiniZinc/MiniZinc.tgz.txt, docsets/MiniZinc/README.md, docsets/MiniZinc/docset.json
Note the version number: the previous one was just entirely incorrect, so this one only _appears_ to be lower, while actually being the latest release.
I've also added a bunch of new indexed entities, cleaned up the existing ones, and improved the generation README.
=> Major improvements to MiniZinc docset

docsets/Haxe/Haxe.tgz.txt, docsets/Haxe/README.md, docsets/Haxe/docset.json
Updated haxe version and added entries for various fields (constructors, variables, methods, fields in typedefs, values in enums).
=> Haxe 4.0.5

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Updating Boto3 docset to version 1.13.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.10.4

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.10.5

docsets/Qt_for_Python/Qt_for_Python.tgz.txt, docsets/Qt_for_Python/versions/5.14.2.1/Qt_for_Python.tgz.txt
https://github.com/acbetter/qt-for-python-to-dash-docset/issues/2
=> Update docset for Qt for Python 5.14.2.1

docsets/JUCE/docset.json
just wanted to make sure this was the right way to introduce versioning. i don't want the `6.0.0-preview` version to be the default, so i left the version tag at `5.4.7`. thanks!
=> add juce6 preview docs and try supporting multiple versions

docsets/Tailwind_CSS/docset.json, docsets/Tailwind_CSS/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/1.4/tailwindcss.tgz.txt
doc has been updated, and docset is cleaner now. got rid of useless JS and mostly everything is offline now (except unsplash images, at least for now).
=> update tailwindcss to 1.4(.5) + make it even more offline!

docsets/Tiki/docset.json, docsets/Tiki/tiki.tgz.txt
add:
* playground
* modules
* tracker fields
* wiki syntax
* online redirection
* Dash 5 description feature
=> update Tiki docset

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.11.0

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.0-preview/JUCE.tgz.txt, docsets/JUCE/versions/6.0.0-preview1/JUCE.tgz.txt
update the juce6 preview docs.
=> update juce-6 preview docs

docsets/Tailwind_CSS/docset.json, docsets/Tailwind_CSS/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/1.4/tailwindcss.tgz.txt
currently for palettes and tables. rest will come later (some issues with inputs).
=> add dark mode for some of TailwindCSS color palettes and tables

docsets/xgboost/README.md, docsets/xgboost/docset.json, docsets/xgboost/xgboost.tgz.txt
=> Dash docs for XGBoost 1.1.1

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.0-preview1/JUCE.tgz.txt
update juce6 to the lastest preview
=> juce-6-preview2 update

docsets/MLflow/MLflow.tgz.txt, docsets/MLflow/docset.json
=> bump MLflow version to v1.9.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.11.1

docsets/Vault/docset.json
Vault:
- 1.4.3
Fixed Terraform 0.12.28 indexing
=> Vault & Terraform fix

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.0/JUCE.tgz.txt
=> juce 6.0.1

docsets/Alfred_4/alfred-4.tgz.txt, docsets/Alfred_4/docset.json
sorry, Alfred released a new minor version (new features) the day after i made the Docset 😅️
so here's an update. and i will keep minor specific versions.
=> update Alfred 4 to 4.1.x, save specific versions

docsets/XMake/docset.json, docsets/XMake/versions/2.3.5/Readme.md
=> XMake v2.3.5

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Updating Boto3 docset to version 1.14.23

docsets/AWS_CLI/docset.json
This is an automatic PR. Please report issues to https://github.com/roberth-k/dash-docset-aws-cli.
=> aws-cli 2.0.34

docsets/Tailwind_CSS/README.md, docsets/Tailwind_CSS/docset.json, docsets/Tailwind_CSS/tailwindcss.tgz.txt
* update tailwind to 1.5.x (2)
* update README to send to new moved repo for issues or questions
=> update tailwind to 1.5.2

docsets/MLflow/MLflow.tgz.txt, docsets/MLflow/docset.json
Released on July 20.
Signed-off-by: Gergely Imreh <gergely.imreh@faculty.ai>
=> update MLflow to 1.10.0

docsets/Tailwind_CSS/README.md, docsets/Tailwind_CSS/docset.json, docsets/Tailwind_CSS/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/1.0/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/1.1/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/1.2/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/1.4/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/1.5.x/tailwindcss.tgz.txt
* delete all versions that TailwindCSS don't keep themselves. i'll keep copies on my own repo just in case someone needs it. will clean Dash repo and interface
* fix README link to new repo
=> update TailwindCSS to 1.6

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.11.2

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Updating Boto3 docset to version 1.14.44

docsets/MLflow/MLflow.tgz.txt, docsets/MLflow/README.md, docsets/MLflow/docset.json
Latest version released 2020/08/31
=> MLflow: bump to version 1.11.0

docsets/AWS_CLI/docset.json
Reverts Kapeli/Dash-User-Contributions#2959
=> Revert "aws-cli 2.0.45"

docsets/discord.js/README.md, docsets/discord.js/docset.json
=> Update discord.js to v12.3.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.11.3

docsets/AWS_CLI/docset.json
Reverts Kapeli/Dash-User-Contributions#3007
=> Revert "aws-cli 2.0.54"

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.1/JUCE.tgz.txt
=> juce-6.0.4

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.12.0

docsets/MLflow/MLflow.tgz.txt, docsets/MLflow/docset.json
=> MLFlow: bump to version 1.12.0

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.12.1

docsets/MLflow/MLflow.tgz.txt, docsets/MLflow/docset.json
Latest one, released on 19 Nov 2020.
=> MlFlow: bump to v1.12.1

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.4/JUCE.tgz.txt
=> juce 6.0.5

docsets/MLflow/MLflow.tgz.txt, docsets/MLflow/README.md, docsets/MLflow/docset.json
=> MLflow: bump version to 1.13.1

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Updating Boto3 docset to version 1.16.51

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.5/JUCE.tgz.txt
=> juce-6.0.6

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.6/JUCE.tgz.txt
=> update juce to 6.0.7

docsets/Kotlin/README.md, docsets/Kotlin/docset.json, docsets/Kotlin/kotlin.tgz.txt
Hello, I'm fairly new to these docsets, but I've noticed that Kotlin docset is pretty old, so I've made an attempt to update it to latest available version. I've tested it and so far it looks like everything works nicely, but additional checks and validations would be appreciated 😄
* Kotlin docset updated to 1.4.21
* Added CSS tweaks to remove static headers, footers and navigation components (should probably resolve [this issue](https://github.com/Kapeli/Dash-User-Contributions/issues/3030))
* Updated Readme file for docset with my data and URL to my version of `kotlin2docset` repo, which contains description of additional CSS fixes
=> Updated Kotlin to 1.4.21

docsets/Elm/Elm.tgz.txt, docsets/Elm/README.md, docsets/Elm/docset.json
January update of packages + add link redirection from the generated pages
=> Elm - packages from 2021-01-28

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.12.2

docsets/Elm/Elm.tgz.txt, docsets/Elm/README.md, docsets/Elm/docset.json
New docset after such a short time because I'm testing testing the semi-automatic generation of it. And it seems it is working 👍
=> New Elm packages from 2021-01-31

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.12.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.12.4

docsets/Terraform/docset.json
closes https://github.com/Kapeli/Dash-User-Contributions/issues/3214
=> terraform 0.14.8 docset

docsets/MLflow/MLflow.tgz.txt, docsets/MLflow/docset.json
Latest one released 2021-03-01.
=> MLflow: bump latest version to 1.14.1 and add missing 1.14.0 version to list

docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.7/JUCE.tgz.txt
=> juce-6.0.8

docsets/WPILib/README.md, docsets/WPILib/docset.json
- Added online redirection URL
=> Update WPILib javadocs to 2021.2.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.13.0

docsets/Kotlin/Kotlin.tgz.txt, docsets/Kotlin/docset.json
* Docset updated to latest Kotlin version 1.5.0
* Removed @pthariensflame from `author` field (sorry 😞 )
=> Updated Kotlin docset to version 1.5.0

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.13.1

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.3.8
=> update PytorchLightning Doc to version 1.3.8

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.13.2

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.4.1
=> update PytorchLightning Doc to version 1.4.1

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.4.2
=> update PytorchLightning Doc to version 1.4.2

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.4.4
=> update PytorchLightning Doc to version 1.4.4

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.13.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.14.0

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.0
=> update PytorchLightning Doc to version 1.5.0

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.1
=> update PytorchLightning Doc to version 1.5.1

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.14.2

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.2
=> update PytorchLightning Doc to version 1.5.2

docsets/ClickHouse/ClickHouse.tgz.txt, docsets/ClickHouse/docset.json, docsets/ClickHouse/versions/21.9.4.35/ClickHouse.tgz.txt
And remove version 21.9.4.35, I got the version number wrong back then.
=> Update ClickHouse docset to 21.11.3.6

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.4
=> update PytorchLightning Doc to version 1.5.4

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.5
=> update PytorchLightning Doc to version 1.5.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.14.3

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.7
=> update PytorchLightning Doc to version 1.5.7

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.8
=> update PytorchLightning Doc to version 1.5.8

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.9
=> update PytorchLightning Doc to version 1.5.9

docsets/Tailwind_CSS/docset.json, docsets/Tailwind_CSS/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/3.0.x/tailwindcss.tgz.txt
fixes some bad overflow on small screens.
=> add update on tailwindcss 3.0.x

docsets/WP-CLI/README.md, docsets/WP-CLI/docset.json
This docset was way out of date. I've updated it to the latest version and filled in the missing versions.
Hope I did everything right. Let me know if it's not correct.
Props to @schlessera for helping out with the WP-CLI repo today.
=> WP-CLI: Update to latest version (2.6) and fill in missing versions

docsets/Tailwind_CSS/docset.json, docsets/Tailwind_CSS/tailwindcss.tgz.txt, docsets/Tailwind_CSS/versions/3.0.x/tailwindcss.tgz.txt
apologies for the quick succession in updates. many changes in 3.0.18 so it took a few days to update to that new doc format.
tested through the docsetcontrib.
=> update tailwind to doc 3.0.18

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.5.10
=> update PytorchLightning Doc to version 1.5.10

docsets/LLVM/docset.json
LLVM 15 - [doc](https://llvm.org/docs/index.html)
=> Latest LLVM Doc

docsets/Envoy/Envoy.tgz.txt, docsets/Envoy/docset.json
is it ok to submit multiple versions in one shot?
=> Update Envoy docset with versions (1.18-1.21)

docsets/JUCE/docset.json, docsets/JUCE/versions/6.1.0/JUCE.tgz.txt
=> juce 6.1.6

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.15.0

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.6.0
=> update PytorchLightning Doc to version 1.6.0

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.6.1
=> update PytorchLightning Doc to version 1.6.1

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.6.2
=> update PytorchLightning Doc to version 1.6.2

docsets/tldr/docset.json
=> Update TLDR pages docset to 0.0.3.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.15.1

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.6.3
=> update PytorchLightning Doc to version 1.6.3

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.6.4
=> update PytorchLightning Doc to version 1.6.4

docsets/Purpur/Purpur.tgz.txt, docsets/Purpur/versions/1.19/Purpur.tgz.txt
Replaced the docsets deployed in the previous pull request #3754, as they were missing methods defined in interfaces.
=> Purpur 1.19 - updating the corrupted docset

docsets/Paper/Paper.tgz.txt, docsets/Paper/versions/1.19/Paper.tgz.txt
Replaced the docsets deployed in the previous pull request #3753, as they were missing methods defined in interfaces.
=> Paper 1.19 - updating the corrupted docset

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Updated boto3 docs by following the instructions in the existing folder.
Thanks!
=> Update boto3 to 1.24.24

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.16.0

docsets/PytorchLightning/docset.json
Here is the link to the doc: https://www.dropbox.com/s/qslmv2nc6ychely/PytorchLightning.tgz?dl=0
=> update PytorchLightning Doc to version 1.6.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.16.1

docsets/Godot/docset.json
[Download docset](https://drive.google.com/file/d/10L5PqqMMvD5rtlfHDbfCRIFDPpF8gqJ9/view?usp=sharing) (180MB)
=> update godot docset to the latest stable version (3.5)

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.7.1
=> update PytorchLightning Doc to version 1.7.1

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
DP4 modified some dictionary entries updating them and also added further examples of syntax.
Some new items also added.
=> Updated to include LC10DP4 dictionary changes

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.7.2
=> update PytorchLightning Doc to version 1.7.2

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.7.5
=> update PytorchLightning Doc to version 1.7.5

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.17.0

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.7.6
=> update PytorchLightning Doc to version 1.7.6

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.7.7
=> update PytorchLightning Doc to version 1.7.7

docsets/JUCE/docset.json
=> juce 7.0.2

docsets/tldr/docset.json
=> Update TLDR pages docset to 0.0.3.6

docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Update boto3 to 1.26.6

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.8.1
=> update PytorchLightning Doc to version 1.8.1

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.8.2
=> update PytorchLightning Doc to version 1.8.2

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.8.3
=> update PytorchLightning Doc to version 1.8.3

docsets/ncurses/README.md
Change title in `docsets/ncurses/README.md` from "Sample Docset" to "ncurses"
=> Set title for ncurses README

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.8.4
=> update PytorchLightning Doc to version 1.8.4

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.18.0

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.8.6
=> update PytorchLightning Doc to version 1.8.6

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.19.0

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
I added my Mastodon profile, as I'm using that more than Twitter now. Hope that's ok; happy to revert to just Twitter if that's preferred.
=> Update boto3 to 1.26.44

docsets/XMake/docset.json
Latest version: https://xmake.io/#/about/changelog
=> XMake v2.7.5

docsets/Powershell/docset.json
Released by GitHub Actions at https://github.com/tddschn/powershell-docset/releases/tag/v7.3.1.
Update docset.json and move docset tgz to versions dir.
=> Add Powershell 7.3 docset

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.9.0
=> update PytorchLightning Doc to version 1.9.0

docsets/JUCE/docset.json, docsets/JUCE/versions/7.0.2/JUCE.tgz.txt
=> juce 7.0.4

docsets/Matrix/docset.json
The tgz archive has already been updated as part of https://github.com/Kapeli/Dash-User-Contributions/pull/3989
=> Matrix 1.5 (Fix version in docset.json)

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.9.1
=> update PytorchLightning Doc to version 1.9.1

docsets/JUCE/docset.json, docsets/JUCE/versions/7.0.4/JUCE.tgz.txt
=> juce 7.0.5

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.9.2
=> update PytorchLightning Doc to version 1.9.2

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
=> Update boto3 to 1.26.70

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.9.3
=> update PytorchLightning Doc to version 1.9.3

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 1.9.4
=> update PytorchLightning Doc to version 1.9.4

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.20.0

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 2.0.0
=> update PytorchLightning Doc to version 2.0.0

docsets/AWS_CloudFormation_Template_Reference/docset.json
Updated to latest docs from 2023.03.20
=> Update AWS CloudFormation docs to 2023.03.20

docsets/Boto3/Makefile, docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
As discussed in #4214 this PR does not directly include the tgz file due to its size. Here is a [download link](https://sewardjm-boto3-dash-docset.s3.us-east-1.amazonaws.com/boto3.tgz?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCWV1LXdlc3QtMiJIMEYCIQDp6k9xlf6ji7R9fva0BYWGWqJTlXk46DnaVyaQ%2B%2F7fMwIhAIddRU1oXP5r1kwyBPbKgsuU7c%2FOqQ4djeTMpbLLSF01Ku8CCKn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMDA4NzIwNzQ3MzgxIgxSBLDNLTdgWPYZtLoqwwJBeZFps0mlNnWYUksmAvQfrTJVyNSt0uKfXjz9xu9YbC4sqUT%2BWYlYzYVTa8PUZiRrhuOcaTI8Igj9FcWvdA2OljWBeBTEdGcYhfO1IfQwmQ8%2BCcrJ%2Fidma0i7n20x5OooT%2BNvzDGdbq1oimPx77mi10%2BBxvfRB0zt2SNWsb8Ft9ibOknQ4h7WdFyJ9fqrgJws6g7x6hLosPLCMKUiWjdlUezHI1P4ZKAuRTqBGkJOjjHVsTRE6Gm%2B8N3wM1uMo89iNelfw%2FCoweyfvB%2BZd%2BrI2Ft2U5dElvd …
=> Update boto3 to 1.26.96

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 2.0.1
=> update PytorchLightning Doc to version 2.0.1

docsets/pytest/docset.json
Update pytest docset to current version.
=> Update pytest docset to 7.3.0

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.76.0-1681992533
- Generated from: [yo-ga/dash-docset-aws-cdk-python](https://github.com/yo-ga/dash-docset-aws-cdk-python/)
- Change log
- Release v2.76.0-1681992533
=> AWS-CDK-Python v2.76.0-1681992533

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 2.0.2
=> update PytorchLightning Doc to version 2.0.2

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.20.1

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.77.0-1682611459
- Generated from: [yo-ga/dash-docset-aws-cdk-python](https://github.com/yo-ga/dash-docset-aws-cdk-python/)
- Change log
- Release v2.77.0-1682611459
=> AWS-CDK-Python: v2.77.0-1682611459

docsets/altair/README.md, docsets/altair/docset.json
Updated Altair docs to version 4.2.
=> Altair 4.2 docs

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.78.0-1683202746
- Change log
- Release v2.78.0-1683202746
=> AWS-CDK-Python v2.78.0-1683202746

docsets/statsmodels/README.md, docsets/statsmodels/docset.json, docsets/statsmodels/statsmodels.tgz.txt
Dash docs for statsmodels version 0.14.
=> Updated statsmodels to version 0.14

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another patch version update.
=> Update Vaadin to version 8.20.2

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.83.0-1686226161
- Change log
- Release v2.83.0-1686226161
=> AWS-CDK-Python v2.83.0-1686226161

docsets/PytorchLightning/docset.json
update PytorchLightning Doc to version 2.0.3
=> update PytorchLightning Doc to version 2.0.3

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Yet another patch version update.
=> Update Vaadin to version 8.20.3

docsets/Boto3/Makefile, docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary is available at https://d24v0t7zqzj9pw.cloudfront.net/1.26.143/boto3.tgz (for 90d).
Thanks!
=> Update boto3 to 1.26.143

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.85.0-1687432022
- Change log
- Release v2.85.0-1687432022
=> AWS-CDK-Python v2.85.0-1687432022

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.86.0-1688123656
- Change log
- Release v2.86.0-1688123656
=> AWS-CDK-Python v2.86.0-1688123656

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.88.0-1689937567
- Change log
- Release v2.88.0-1689937567
=> AWS-CDK-Python v2.88.0-1689937567

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file available at https://d24v0t7zqzj9pw.cloudfront.net/1.28.3/boto3.tgz for 90d from today.
Thanks!
=> Update boto3 to 1.28.3

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.89.0-1690628745
- Change log
- Release v2.89.0-1690628745
=> AWS-CDK-Python v2.89.0-1690628745

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.90.0-1691233432
- Change log
- Release v2.90.0-1691233432
=> AWS-CDK-Python v2.90.0-1691233432

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.91.0-1691752668
- Change log
- Release v2.91.0-1691752668
=> AWS-CDK-Python v2.91.0-1691752668

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.92.0-1692184110
- Change log
- Release v2.92.0-1692184110
=> AWS-CDK-Python v2.92.0-1692184110

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.93.0-1692875295
- Change log
- Release v2.93.0-1692875295
=> AWS-CDK-Python v2.93.0-1692875295

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.94.0-1693652635
- Change log
- Release v2.94.0-1693652635
=> AWS-CDK-Python v2.94.0-1693652635

docsets/JUCE/docset.json, docsets/JUCE/versions/7.0.5/JUCE.tgz.txt
=> juce 7.0.7

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.95.1-1694257592
- Change log
- Release v2.95.1-1694257592
=> AWS-CDK-Python v2.95.1-1694257592

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.96.1-1694776429
- Change log
- Release v2.96.1-1694776429
=> AWS-CDK-Python v2.96.1-1694776429

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.96.2-1694862984
- Change log
- Release v2.96.2-1694862984
=> AWS-CDK-Python v2.96.2-1694862984

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.97.1-1695726733
- Change log
- Release v2.97.1-1695726733
=> AWS-CDK-Python v2.97.1-1695726733

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.99.0-1695899295
- Change log
- Release v2.99.0-1695899295
=> AWS-CDK-Python v2.99.0-1695899295

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.99.1-1696158343
- Change log
- Release v2.99.1-1696158343
=> AWS-CDK-Python v2.99.1-1696158343

docsets/PyPDF/docset.json, docsets/Requests/docset.json, docsets/SymPy/docset.json, docsets/xarray/README.md, docsets/xarray/docset.json
- bump xarray
- also update my name in some docset.json files which I contributed.
=> bump xarray

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.100.0-1696677095
- Change log
- Release v2.100.0-1696677095
=> AWS-CDK-Python v2.100.0-1696677095

docsets/Tailwind_CSS/docset.json
- Take account of the padding and adjust the scroll gap
- Find more classes and modifiers from outside of tables
=> Update Tailwind CSS docset to 3.3.3-1

docsets/BigQuery_Standard_SQL/README.md, docsets/BigQuery_Standard_SQL/docset.json, docsets/Presto/README.md, docsets/Presto/docset.json, docsets/Trino/README.md, docsets/Trino/docset.json
#4632 introduced my last name in the non-capitalized form, so I decided to use it consistently.
https://github.com/Kapeli/Dash-User-Contributions/blob/8809ca268eefeaa690b7346b23fb315ec887668b/docsets/Tailwind_CSS/docset.json#L6
=> Unify the notation of my name

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.101.0-1697281710
- Change log
- Release v2.101.0-1697281710
=> AWS-CDK-Python v2.101.0-1697281710

docsets/tldr/README.md, docsets/tldr/docset.json
Hello,
This update includes a change to the author information. The original author has been unresponsive for some time. I have been maintaining this docset, and I think it's worth making it official.
Thanks,
Chad
=> Update TLDR pages docset to 0.0.3.7 and change author

docsets/Tailwind_CSS/docset.json
- Add support for dark/light color scheme switching
=> Update Tailwind CSS docset to 3.3.3-4

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.102.0-1697714244
- Change log
- Release v2.102.0-1697714244
=> AWS-CDK-Python v2.102.0-1697714244

docsets/tldr/docset.json
=> Update TLDR pages docset to 2023-11-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.103.0-1698319088
- Change log
- Release v2.103.0-1698319088
=> AWS-CDK-Python v2.103.0-1698319088

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.104.0-1699302046
- Change log
- Release v2.104.0-1699302046
=> AWS-CDK-Python v2.104.0-1699302046

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.108.0-1699959780
- Change log
- Release v2.108.0-1699959780
=> AWS-CDK-Python v2.108.0-1699959780

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.108.1-1700046292
- Change log
- Release v2.108.1-1700046292
=> AWS-CDK-Python v2.108.1-1700046292

docsets/D/docset.json
Dlang ver: 2.105.3
Differ: `core.stdcpp.*` in index added
=> D language update

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.110.0-1700218984
- Change log
- Release v2.110.0-1700218984
=> AWS-CDK-Python v2.110.0-1700218984

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.110.1-1700651296
- Change log
- Release v2.110.1-1700651296
=> AWS-CDK-Python v2.110.1-1700651296

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.111.0-1701169421
- Change log
- Release v2.111.0-1701169421
=> AWS-CDK-Python v2.111.0-1701169421

docsets/Tailwind_CSS/docset.json
- Include images on an external site (images.unsplash.com) for better offline browsing experience
- Remove a redirected page on TailwindUI.com
=> Update Tailwind CSS docset to 3.3.6-2

docsets/Vulkan/docset.json
Fixes https://github.com/Kapeli/Dash-User-Contributions/issues/4722
=> Update Vulkan docset to version 1.3.273

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-01-01

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-02-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.130.0-1708686165
- Change log
- Release v2.130.0-1708686165
=> AWS-CDK-Python v2.130.0-1708686165

docsets/Tailwind_CSS/docset.json
- typography-plugin is now an external resource.
=> Update Tailwind CSS docset to 3.4.1-14

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.131.0-1709377101
- Change log
- Release v2.131.0-1709377101
=> AWS-CDK-Python v2.131.0-1709377101

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-03-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.132.0-1709982201
- Change log
- Release v2.132.0-1709982201
=> AWS-CDK-Python v2.132.0-1709982201

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.132.1-1710241256
- Change log
- Release v2.132.1-1710241256
=> AWS-CDK-Python v2.132.1-1710241256

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.133.0-1710500476
- Change log
- Release v2.133.0-1710500476
=> AWS-CDK-Python v2.133.0-1710500476

docsets/Kotlin/README.md, docsets/Kotlin/docset.json, docsets/Kotlin/kotlin.tgz.txt
- add Table of Contents to every page
- add kotlin.test docs
- make CSS adjustments automatic
- some general code cleanup
- update to 1.9.20
=> Adjust kotlin docs to add ToC and Test docs

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Tarball is here for 90d: https://d24v0t7zqzj9pw.cloudfront.net/1.34.70/boto3.tgz
Thanks!
=> Bump boto3 to 1.34.70

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.135.0-1712055778
- Change log
- Release v2.135.0-1712055778
=> AWS-CDK-Python v2.135.0-1712055778

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-04-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.137.0-1712833359
- Change log
- Release v2.137.0-1712833359
=> AWS-CDK-Python v2.137.0-1712833359

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.140.0-1714734351
- Change log
- Release v2.140.0-1714734351
=> AWS-CDK-Python v2.140.0-1714734351

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-05-01

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary download is at https://d24v0t7zqzj9pw.cloudfront.net/1.34.90/boto3.tgz for 90d.
Thanks!
=> Update boto3 to 1.34.90

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.141.0-1715252715
- Change log
- Release v2.141.0-1715252715
=> AWS-CDK-Python v2.141.0-1715252715

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.142.1-1716040938
- Change log
- Release v2.142.1-1716040938
=> AWS-CDK-Python v2.142.1-1716040938

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
=> Update Vaadin to version 8.25.2

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.143.0-1716548794
- Change log
- Release v2.143.0-1716548794
=> AWS-CDK-Python v2.143.0-1716548794

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.144.0-1717239855
- Change log
- Release v2.144.0-1717239855
=> AWS-CDK-Python v2.144.0-1717239855

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-06-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.145.0-1717844705
- Change log
- Release v2.145.0-1717844705
=> AWS-CDK-Python v2.145.0-1717844705

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.146.0-1718363117
- Change log
- Release v2.146.0-1718363117
=> AWS-CDK-Python v2.146.0-1718363117

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.147.2-1719572829
- Change log
- Release v2.147.2-1719572829
=> AWS-CDK-Python v2.147.2-1719572829

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file is at https://d24v0t7zqzj9pw.cloudfront.net/1.34.135/boto3.tgz for 90d.
Thanks!
=> Update boto3 to 1.34.135

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.147.3-1719918402
- Change log
- Release v2.147.3-1719918402
=> AWS-CDK-Python v2.147.3-1719918402

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-07-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.151.0-1722683003
- Change log
- Release v2.151.0-1722683003
=> AWS-CDK-Python v2.151.0-1722683003

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-08-01

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file available at https://d24v0t7zqzj9pw.cloudfront.net/1.34.150/boto3.tgz for 90d.
Thanks!
=> Update boto3 to 1.34.150

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.152.0-1723720171
- Change log
- Release v2.152.0-1723720171
=> AWS-CDK-Python v2.152.0-1723720171

docsets/pyspark/README.md, docsets/pyspark/docset.json
#1576 Add `pyspark` version `3.4.0` docset.
=> Add PySpark 3.4.0 docset

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file at https://d24v0t7zqzj9pw.cloudfront.net/1.35.13/boto3.tgz for 90d as usual.
Thanks!
=> Update boto3 to 1.35.13

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-09-01

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-10-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.162.1-1728731317
- Change log
- Release v2.162.1-1728731317
=> AWS-CDK-Python v2.162.1-1728731317

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.163.1-1729681865
- Change log
- Release v2.163.1-1729681865
=> AWS-CDK-Python v2.163.1-1729681865

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.164.1-1729941168
- Change log
- Release v2.164.1-1729941168
=> AWS-CDK-Python v2.164.1-1729941168

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-11-01

docsets/OpenXR/docset.json
Newest OpenXR documentation version.
=> OpenXR 1.1.42

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.166.0-1730977875
- Change log
- Release v2.166.0-1730977875
=> AWS-CDK-Python v2.166.0-1730977875

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.167.1-1731755420
- Change log
- Release v2.167.1-1731755420
=> AWS-CDK-Python v2.167.1-1731755420

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.170.0-1732360326
- Change log
- Release v2.170.0-1732360326
=> AWS-CDK-Python v2.170.0-1732360326

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.171.0-1732619721
- Change log
- Release v2.171.0-1732619721
=> AWS-CDK-Python v2.171.0-1732619721

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.172.0-1733570060
- Change log
- Release v2.172.0-1733570060
=> AWS-CDK-Python v2.172.0-1733570060

docsets/OpenXR/docset.json
New OpenXR documentation version.
=> OpenXR 1.1.43

docsets/tldr/docset.json
=> Update TLDR pages docset to 2024-12-01

docsets/UnicodeCharacters/docset.json
- Show character in search
- Make characters searchable by alias
- Make characters searchable by character
- Skip representation of non-displayable characters
=> UnicodeCharacters: Misc. improvements

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file at https://d24v0t7zqzj9pw.cloudfront.net/1.35.79/boto3.tgz for 90d.
Thanks!
=> Bump boto3 to 1.35.79

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.174.0-1736075042
- Change log
- Release v2.174.0-1736075042
=> AWS-CDK-Python v2.174.0-1736075042

docsets/tldr/docset.json
=> Update TLDR pages docset to 2025-01-01

docsets/tldr/docset.json
=> Update TLDR pages docset to 2025-02-01

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file at https://d24v0t7zqzj9pw.cloudfront.net/1.36.23/boto3.tgz for 90d.
Thanks!
=> Bump boto3 to 1.36.23

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.181.1-1741022018
- Change log
- Release v2.181.1-1741022018
=> AWS-CDK-Python v2.181.1-1741022018

docsets/Scikit/README.md, docsets/Scikit/docset.json
Updates scikit-learn docs to 1.6.1
=> Updates scikit-learn docs to 1.6.1

docsets/tldr/docset.json
=> Update TLDR pages docset to 2025-03-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.182.0-1741259094
- Change log
- Release v2.182.0-1741259094
=> AWS-CDK-Python v2.182.0-1741259094

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.185.0-1742468583
- Change log
- Release v2.185.0-1742468583
=> AWS-CDK-Python v2.185.0-1742468583

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.187.0-1743505520
- Change log
- Release v2.187.0-1743505520
=> AWS-CDK-Python v2.187.0-1743505520

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file at https://d24v0t7zqzj9pw.cloudfront.net/1.37.31/boto3.tgz for 90d.
Thanks!
=> Bump boto3 to 1.37.31

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.188.0-1743764631
- Change log
- Release v2.188.0-1743764631
=> AWS-CDK-Python v2.188.0-1743764631

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.190.0-1744887855
- Change log
- Release v2.190.0-1744887855
=> AWS-CDK-Python v2.190.0-1744887855

docsets/Presto/docset.json
This also fixes internal links that are specified by absolute URLs.
=> Update Presto docset to 0.292

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.194.0-1746183894
- Change log
- Release v2.194.0-1746183894
=> AWS-CDK-Python v2.194.0-1746183894

docsets/tldr/docset.json
=> Update TLDR pages docset to 2025-05-01

docsets/PyQGIS/README.md, docsets/PyQGIS/docset.json, docsets/PyQGIS/pyqgis.patch, docsets/QGIS/README.md, docsets/QGIS/docset.json
Updating QGIS and PyQGIS docsets to version 3.42.2
Docset for PyQGIS is in the commit.
Docset for QGIS is [downloadable here](https://share.oslandia.net/s/xpMzSHSjLYqgBKK).
Thanks! 😉
=> Update QGIS and PyQGIS to 3.42.2

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.197.0-1747825658
- Change log
- Release v2.197.0-1747825658
=> AWS-CDK-Python v2.197.0-1747825658

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary download at https://d24v0t7zqzj9pw.cloudfront.net/1.38.31/boto3.tgz for 90d as usual :)
Thanks!
=> Bump boto3 to 1.38.31

docsets/tldr/docset.json
=> Update TLDR pages docset to 2025-06-01

docsets/tldr/docset.json
=> Update TLDR pages docset to 2025-07-01

docsets/Scikit/README.md, docsets/Scikit/docset.json, docsets/Scikit/scikit-learn-1.2.2.tgz.txt, docsets/Scikit/scikit-learn.tgz.txt
Added latest Scikit-Learn version 1.7.0 Dash docset.
=> Scikit-Learn 1.7.0 Docset

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.206.0-1752750633
- Change log
- Release v2.206.0-1752750633
=> AWS-CDK-Python v2.206.0-1752750633

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.210.0-1754565008
- Change log
- Release v2.210.0-1754565008
=> AWS-CDK-Python v2.210.0-1754565008

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary download at https://d24v0t7zqzj9pw.cloudfront.net/1.40.3/boto3.tgz for 90d.
Thanks!
=> Bump boto3 to 1.40.3

docsets/tldr/docset.json
=> Update TLDR pages docset to 2025-08-01

docsets/AWS_CDK_Python/docset.json
- Latest version: v2.211.0-1755083287
- Change log
- Release v2.211.0-1755083287
=> AWS-CDK-Python v2.211.0-1755083287

docsets/UnicodeCharacters/docset.json
=> Update UnicodeCharacters to 17.0.0
