docsets/Pin/README.md, docsets/Pin/docset.json
Fix the issue that there're some entries didn't has the `type` set, 148 entries were updated to `define.`
=> Repull pin docset

docsets/RFCs/docset.json
This docset is over the 100 mb limit, so I've not included the tarball in this commit. The current 1.2 version can be obtained from https://github.com/willnorris/rfcdash/releases/download/v1.2/RFCs.tgz
fixes willnorris/rfcdash#3
=> update RFCs docset to v1.2

docsets/Eigen/Eigen.tgz.txt, docsets/Eigen/README.md, docsets/Eigen/docset.json
It comes from the docset created by Egor Larionov. The docset is recompiled to fix the formula picture bugs in the version compiled by Egor Larionov, by enabling LaTeX in compilation.
Nothing else has been changed, except adding my information in the Readme.md. All rights are still reserved by the original author Egor Larionov. Please also let Egor Larionov know this update. 
Thanks!
=> Update Eigen v3.2.4 docset created by Egor Larionov

docsets/Kotlin/docset.json
The current Kotlin index only has `Guides` with weird names like `stdlib / kotlin.Boolean`. This PR fixes the names and sets the correct types.
Sorry for bugging you again today. :no_mouth:
=> Better Kotlin index

docsets/Kotlin/README.md, docsets/Kotlin/docset.json
Updated very outdated Kotlin docset (they changed a lot for 1.0-beta). Does the following cause an issue?
"version": "1.0.0-beta-1103"
Or should I set it to `1.0.0/beta-1103`, which would be a little bit confusing I guess.
=> updated Kotlin docset to 1.0.0-beta-1103

docsets/Pythonista/README.md, docsets/Pythonista/docset.json
Updated docsets to Pythonista 2.1 for legacy version, & Pythonista 3.0 for
current version. Also reduced the docset size, because Pythonista
3.0's documentation includes a large number of 3rd party modules 
that Dash already has specific docsets for, and it would be very time
consuming to attempt to include all of them into one docset package.
=> Update Pythonista 3 docset & add legacy Pythonista 2.1 docset

docsets/SymPy/README.md, docsets/SymPy/SymPy.tgz.txt, docsets/SymPy/docset.json
I updated the docsets for SymPy (symbolic math in python) to version 1.0 since the currently available docset for version 0.7.5. (year: 2014) is outdated. I also included the version 0.7.6.1 which can be still found  in a lot of Python installations. I hope the contribution is helpful, can be used and meets the requirements. If any issues occur or i made a mistake in packaging please let me know.
=> Added docsets for SymPy 0.7.6.1 and 1.0.0.

docsets/FFmpeg/docset.json, docsets/Libav/docset.json
update ffmpeg to 3.2 and libav to 12.
And I also removed lite version of guides, and fixed some section name error.
I don't know if this is a bug of Dash, if a section name contains character `/`, then the section are ignored, So I have to convert all `/` characters in section name to `|`. That however looks strange.
BTW, waiting the test result will make me like I'm waiting a  trial.  Ha ha .
=> ffmpeg 3.2 and libav 12 docset version update

docsets/Terraform/README.deprecated.md, docsets/Terraform/README.md, docsets/Terraform/Terraform.tgz.txt, docsets/Terraform/docset.json
Terraform doc management has been changed since v0.10.0 and required several changes to use the existing code and generate the dash docset.
In addition, the generator script contains a fix for separating terraform data and resources at the SQlite index.
Previous docset versions will be fixed in a separate pull request.
=> Updated Terraform Docset to v0.10.6

docsets/Crystal/docset.json
This updates the Crystal Docset to 0.23.1 and removes the sidebar from the API docs using CSS.
The sidebar in the API docs did show a navigation and search for the types which duplicated functionality already provided equally well by Dash itself and took up screen space.
The following CSS changes where made to hide the types list in `css/style.css`:
```css
#types-list { display: none; }
#main-content { left: 0; }
```
I have left the menu for the Crystal User Guide, because it can be hidden by the user and provides the necessary hierarchy that is lacking from the generated TOC.
=> Update Crystal docset to 0.23.1

docsets/Wagtail/README.md
Also moved the icon note to its own heading as it is not really part of the normal instructions
=> Clarification about docset archive locations (Wagtail)

docsets/Scikit/README.md, docsets/Scikit/build.sh, docsets/Scikit/docset.json, docsets/Scikit/userguide.py
* Update from 0.19.0 to 0.19.1
* Use recent doc2dash custom parser feature to enhance docs
* add user guides to TOC
* prefix some user guide titles to indicate structure and subtypes
* remove attributes from TOC as not consistently exported by
numpydoc/doc2dash at present
* Add index page
* Add a build script to automatically acquire and build docs for a given version tag, and package them in preparation for committing to Dash-User-Contributions
=> Update and improve scikit-learn docs

docsets/LiveCode/docset.json
widget libraries are now typed as "modules". Control Structures need to be capitalized.
=> adjust for nomenclature change

docsets/RFCs/README.md, docsets/RFCs/docset.json
I updated the RFC docset, and it passed the validation using the tool mentioned at #1051.
You can download the archive at
https://cl.ly/0s1k080e1N0K/download/RFCs.docset-v1.5.0.tgz
/cc @willnorris
=> Update RFCs docset to v1.5.0

docsets/Elektra/docset.json
👋 Hi,
this pull request adds a DocSet for the latest version of [Elektra](https://www.libelektra.org). If I should change anything, please just comment below.
By the way: The latest version of XCode does not include the `docsetutil` anymore. Do you have any advice on how to fix the generation of a DocSet via [Doxygen](https://kapeli.com/docsets#doxygen), besides installing an old version of Xcode? 
Kind regards,
René
=> Add DocSet for Elektra 0.8.23

docsets/Jest/docset.json
Related to #1569.
I don't know how to add 2 authors, so forgive me to replace the original author @epitaphmike. The generating scripts are based on https://github.com/epitaphmike/jest-dash with some updates.
Main differences of the docset are,
- Fetch documents from the current Jest website
- Entry types are more than `Section`
- Support to search API and configuration options now, https://github.com/epitaphmike/jest-dash/issues/2
- Keep page header/footer and side menu the same with the website
=> Add Jest@23.1.0

docsets/Seaborn/README.md, docsets/Seaborn/Seaborn.tgz.txt, docsets/Seaborn/docset.json
This PR builds on the work done in https://github.com/Kapeli/Dash-User-Contributions/pull/1060. Seaborn's tutorial and gallery are added as Dash `Guides` and `Samples`, respectively.
=> ENH: Adds seaborn 0.9.0

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Mostly provides API compatibility updates. See full changelog here:
https://github.com/boto/boto3/blob/develop/CHANGELOG.rst
=> Updating boto3 Docset to v1.7.66

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
For a list of changes included in this docset update please see the boto3 changelog:
https://github.com/boto/boto3/blob/develop/CHANGELOG.rst
=> Updating boto3 Docset to v1.7.78

docsets/PeopleTools/PeopleTools.tgz.txt, docsets/PeopleTools/README.md, docsets/PeopleTools/docset.json
Ref #2071
Re-submitting with compression done using Windows Linux Subsystem (instead of in Windows). I tried decompressing on my server that runs Fedora and it decompressed correctly, so hopefully Travis likes it this time.
=> Update PeopleTools to 8.57

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
Line breaks in "Syntax" entries honoured.
Syntax coloring for code blocks contained within the "Description" blocks.
=> More Syntax coloring.

docsets/SuperCollider/versions/3.10/supercollider.tgz.txt
I missed that in this version, the examples in the documentation are loaded by a local JavaScript file. This is the same version of the docset, just with JavaScript enabled.
Let me know if you'd also like me to update the plist that points to the version. I wasn't sure what the protocol was here. Thanks!
=> Enable JavaScript on SuperCollider docSet

docsets/PeopleTools/docset.json
I am on Windows and use Velocity there. I tested the docset and I believe it's working correctly, but I cannot test the installation part. In the past the archive had problems on *nix machines, so I built it using WSL (Windows Sub-system for Linux). Hopefully it works correctly. 🤞
=> Update PeopleTools 8.57 to revision 2

docsets/Chainer/docset.json
This is to update the Chainer (a deep learning framework) docset to the latest v5.4.0.
CC: @mitmul
=> Chainer V5.4.0 docset

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
- Fixed an issue where some files within the docset weren't be updated properly
- Fixed some display issues related to some weirdness between sphinx versions required for building docs and converting to Dash format
=> Updating Boto3 docset to version 1.9.149

docsets/Vaadin/README.md, docsets/Vaadin/docset.json
Fixing last night's update mistake. Includes v8.8.0 (previous) and v8.8.1 (latest).
=> Update Vaadin with versions 8.8.0 and 8.8.1

docsets/RFCs/docset.json
I updated the RFC docset, and it passed the validation:
```
➜  Dash-User-Contributions git:(rfc-160) ✗ wget https://kapeli.com/feeds/zzz/docsetcontrib.tgz && tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify
--2019-08-24 22:52:29--  https://kapeli.com/feeds/zzz/docsetcontrib.tgz
Resolving kapeli.com (kapeli.com)... 23.92.22.81
Connecting to kapeli.com (kapeli.com)|23.92.22.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 141080 (138K) [application/x-tar]
Saving to: 'docsetcontrib.tgz'
docsetcontrib.tgz                                100%[==========================================================================================================>] 137.77K   417KB/s    in 0.3s
2019-08-24 22:52:30 (417 KB/s) - 'docsetcontrib.tgz' saved [141080/141080]
Checking …
```
=> Update RFC docset to v1.6.1

docsets/date-fns/docset.json
Updates date-fns to 2.8.1.
Also filed a PR on iansinnott/date-fns-dash-docset#1 but original author isn't replying, so thought I'd just upstream this myself now.
=> Update date-fns docset to 2.8.1

docsets/Qt_for_Python/README.md, docsets/Qt_for_Python/docset.json
fixes and changes for 5.14 doc style and update doc version
more info see [https://github.com/acbetter/qt-for-python-to-dash-docset/pull/1](https://github.com/acbetter/qt-for-python-to-dash-docset/pull/1)
=> Update Qt for Python (PySide2) to 5.14.2.1

docsets/Jigsaw/README.md, docsets/Laravel_Zero/README.md, docsets/Ploi_API/README.md, docsets/Tailwind_CSS/README.md, docsets/Tiki/README.md
i'm separating the Docsets from the Docset Builder that will be released
soon as its own package/binary. so the READMEs need to reflect this
so that people can report issues on the right repos.
=> update READMEs for a couple of own Docsets

docsets/JUCE/JUCE.tgz.txt, docsets/JUCE/docset.json, docsets/JUCE/versions/6.0.0-preview2/JUCE.tgz.txt
juce 6.0.0 released - making this the default version now but still supporting the last 5.x release as well.
=> juce-6.0.0 final

docsets/TensorFlow/README.md, docsets/TensorFlow/docset.json
The old project (https://github.com/ppwwyyxx/dash-docset-tensorflow) lacks update in the past year but now I've brought it up to date.
Compared to the alternative solution in https://github.com/Kapeli/Dash-User-Contributions/pull/2440, my approach has a more native look that follows the official website, and I also make sure the links are clickable and direct to the correct doc page.
Before:
After:
@reuben , I've updated the authors to reflect contributions in each version. Let me know if that doesn't look good to you. I can also do the same for TensorFlow2 if you like.
=> update TensorFlow 1.15

docsets/ns-3/Info.plist, docsets/ns-3/docset.json
As discussed, this pull request updates the supplementary files for the ns-3.32 docset.
The docset itself you can find under:
https://www.dropbox.com/s/3lmms0ofnbemu2c/ns-3.tgz?dl=0
It would be great if you could process the prior pull request https://github.com/Kapeli/Dash-User-Contributions/pull/3062 first, and put the `ns-3.tgz` provided there under `versions/3.31/`.
Thank you!
=> Updated for ns-3.32

docsets/QGIS/README.md, docsets/QGIS/docset.json
Supersedes #3084 
This PR proposes to update the QGIS docset to new LTR stable version 3.16.
The docset is more than 600 MB, so I pushed it [here](https://www.dropbox.com/s/90660gn65bx3jox/QGIS.tgz?dl=0)
=> New QGIS 3.16 docset

docsets/ns-3/Info.plist, docsets/ns-3/docset.json, docsets/ns-3/ns-3.tgz.txt
This PR updates the ns-3 docset to version 3.33.
As was the case with the last two updates, the docset size surpasses Github's 100MB limit. 
You can find it [via this Dropbox link](https://www.dropbox.com/s/szuktadtdysfpq2/ns-3.tgz?dl=0).
It would be great if you could place the old version under `versions/3.32/ns-3.tgz`.
Thank you!
=> Update to ns-3.33

docsets/Scikit/build.sh, docsets/Scikit/docset.json
Closes #3173. 
- Adds updated docset tarball. 
- Adds missing `sphinx-prompt` package to `build.sh`.
- Updates `docset.json` file.
=> Update scikit-learn docset to 0.24.1 (closes #3173)

docsets/UnrealEngine4/docset.json
I Updated the UE4 docset to 4.26. I skipped version 4.25 (I can only scrap the current version form their website)
Since the compressed docset is about 3GB in size I have to upload it via google drive.
https://drive.google.com/file/d/15fnP4Ne2LFF6sHZr1nPGkZGf25h8lFIl/view?usp=sharing
Thanks for helping me fix the dark mode issues.
I also improved the category detection a lot and added an online fallback url.
Docset was generated with https://github.com/lolleko/unreal-docset
=> Update Unreal Engine docset to 4.26

docsets/Nomad/docset.json
Add recent Nomad docsets, and rebuilds older docsets to fix issues with broken URLs.
Note, this is my first time using `/` to submit updates to existing docset versions, as described in [Docset Versioning Guidelines](https://github.com/Kapeli/Dash-User-Contributions/wiki/Docset-Versioning-Guidelines). I'm not sure if I am using the correct directory layout. I generated a custom [docset feed](https://kapeli.com/docsets#dashdocsetfeed) to test this.
```xml
<entry>
<version>1.1.2</version>
<url>http://localhost:8000/Nomad.tgz</url>
<other-versions>
<version>
<name>1.1.2/sub_version</name>
</version>
</other-versions>
</entry>
```
I observed Dash attempts to download the docsets from the path `/versions/Nomad/1.1.2/sub_version/Nomad.tgz`, whereas the directory hierarchy in this commit is …
=> Update Nomad docsets

docsets/ns-3/Info.plist, docsets/ns-3/docset.json
This updates the ns-3 docset to the latest version. As previously, this PR only includes the metadata, the actual docset can be found here: https://www.dropbox.com/s/z2ipcxx3v4sty41/ns-3.tgz?dl=0
=> Update to ns-3.34

docsets/statsmodels/README.md, docsets/statsmodels/docset.json, docsets/statsmodels/statsmodels.tgz.txt, docsets/statsmodels/versions/0.12.0/statsmodels.tgz.txt
Update to Dash docset package for statsmodels 0.13.1, which includes 8 bug fixes for the 0.13 branch and brings initial support for Python 3.10.
=> Requesting update of statsmodels docset to version 0.13.1

docsets/WP-CLI/README.md, docsets/WP-CLI/docset.json
@rosswintle Thanks for adding the latest versions of the WP-CLI docsets to this repo
This PR reverts the author from @rosswintle back to myself, as I authored the project which generates the WP-CLI docsets: https://github.com/wp-cli/dash-docset-generator
@Kapeli It feels like a safe assumption that `author` should refer to the author who contributed the work of generating the docset, as opposed to the person who executed the generator last, but let me know if I've misunderstood
=> Revert author update

docsets/Godot/README.md, docsets/Godot/docset.json, docsets/Godot/godot.tgz.txt
The actual [`godot.tgz`] can be downloaded from [google drive](https://drive.google.com/file/d/10L5PqqMMvD5rtlfHDbfCRIFDPpF8gqJ9/view?usp=sharing) since it's larger than 100MB(186MB).
The docset is generated and optimized with [a custom script](https://github.com/poga/godot-dash-docset).
Please let me know if there's any issue when downloading :)
=> update godot docset to the latest stable (3.4.4)

docsets/JSON_for_Modern_C++/JSON_for_Modern_C++.tgz.txt, docsets/JSON_for_Modern_C++/docset.json
https://github.com/nlohmann/json/releases/tag/v3.11.2 was just released.
Docset documentation was improved and the generated docset should now be on par with the mkdocs documentation (i.e., no missing pages).
=> Update docset JSON_for_Modern_C++ to v3.11.2

docsets/Wagtail/docset.json
This pull request updates wagtail's main version in the `docset.json` file to `version 4.0`
=> Update wagtail's main version

docsets/LiveCode/README.md, docsets/LiveCode/docset.json
location of guide image files had been changed resulting in them being omitted, from docset.
Now corrected.
=> Fix guide image regression

docsets/PEPs/PEPs.tgz.txt, docsets/PEPs/README.md, docsets/PEPs/docset.json
The current PEP docset is scraped from the [Python PEPs website](https://peps.python.org/). I've built the documentation with Sphinx and converted it with `doc2dash` to generate this Docset.
=> Update PEPs docset and build with Sphinx and local links

docsets/Boto3/Makefile, docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
As before, the tgz file is now too big to push directly to github.
The file is available to download from https://d24v0t7zqzj9pw.cloudfront.net/1.26.121/boto3.tgz - this link will function for 90d.
Thanks!
=> Update boto3 to 1.26.121

docsets/QGIS/docset.json
This is the follow-up of #3540 made by @Koyaani and @troopa81 
Updating QGIS documentation to 3.30.3
Because of the size, the documentations can be [downloaded here](https://send.volpes.fr/download/eb51f581609267fa/#GP7pEIXimX7cYFuIAxS4WQ)
=> Update QGIS docset to 3.30

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
As usual, the tar file is available for download at https://d24v0t7zqzj9pw.cloudfront.net/1.28.28/boto3.tgz for 90d.
Thanks!
=> Update boto3 to 1.28.28

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
tgz file is available at https://d24v0t7zqzj9pw.cloudfront.net/1.28.44/boto3.tgz for 90 days from today.
Thanks!
=> Update boto3 to 1.28.44

docsets/Tailwind_CSS/README.md, docsets/Tailwind_CSS/docset.json
The current maintainer @godbout has kindly agreed to transfer the maintainership of this docset to me.
https://github.com/godbout/tailwindcss-dash-docset/issues/34
The new docset for Tailwind CSS 3.3.3 includes all Tailwind CSS classes, modifiers, their CSS properties, functions and directives in the index.
=> Update Tailwind CSS docset to 3.3.3-0 and change the maintainer

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Archive available at https://d24v0t7zqzj9pw.cloudfront.net/1.28.77/boto3.tgz for 90d.
Thanks!
=> Bump boto3 to 1.28.77

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
As usual, the archive is at https://d24v0t7zqzj9pw.cloudfront.net/1.33.11/boto3.tgz for 90d :)
Thanks!
=> Bump boto3 to 1.33.11

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary file is at https://d24v0t7zqzj9pw.cloudfront.net/1.34.26/boto3.tgz for 90d.
Thanks!
=> Bump boto3 to 1.34.26

docsets/Vega/README.md, docsets/Vega/docset.json
- Update documentation for Vega open-source graphing library
- Update https://github.com/Kapeli/Dash-User-Contributions/pull/3398
- Updates contents by rerunning my [generator script](https://github.com/hydrosquall/vega-docset-generator/blob/main/README.md#features)
- From `5.20.2` released [Mar 30 2021](https://github.com/vega/vega/releases/tag/v5.20.2) )  to 
- to latest `5.27.0` released [Jan 3 2024](https://github.com/vega/vega/releases/tag/v5.27.0) . ( Required updating to the site's build script for a [clean output](https://github.com/vega/vega/pull/3280) )
=> feat: update vega docset for Vega 5.27.0

docsets/Vega-Lite/README.md, docsets/Vega-Lite/docset.json
- Vega-Lite is an open source graphing library used in Python, JavaScript, etc
- Update docs originally contributed in https://github.com/Kapeli/Dash-User-Contributions/pull/3383
- Updates contents by rerunning my [generator script](https://github.com/hydrosquall/vega-lite-docset-generator/blob/main/README.md#features)
- From `5.1.0` released [Apr 16 2021](https://github.com/vega/vega-lite/commit/64739639fd85d9be605704c91425d26450d25b9c) )  to 
- to latest `5.16.3` released [Nov 9 2023](https://github.com/vega/vega-lite/releases/tag/v5.16.3) . ( Required making updates to the site's build script for a [clean output](https://github.com/vega/vega-lite/pull/9254) )
=> feat: update vega-lite docset for Vega-Lite 5.16.3

docsets/PyQGIS/docset.json
Updating PyQGIS docset to version 3.36.1.
[Download link (expire in 30 days) for the docset](https://plik.vulpecula.fr/file/wYsy7veGTWLjp8F2/mrFpWfLZETsoLmEe/PyQGIS.tgz?dl=1).
=> Update PyQGIS to 3.36.1

docsets/ACL2/docset.json
Update docs to the latest version:
https://www.cs.utexas.edu/users/moore/acl2/v8-5/combined-manual/index.html\
BTW, can I qualify for a free license of the latest version please? The repo below contains the scripts I've written to generate this docset:
https://github.com/marsmxm/acl2dash
And my email address is marsmxm@gmail.com. Thanks!
=> Update ACL2 docset to v8.5

docsets/Mastodon/Mastodon.tgz.txt, docsets/Mastodon/docset.json
Based on https://github.com/mastodon/documentation/commit/07f305fe820171f023f16e7c77bc06ff06e775f7
The documentation doesn't specifically say Mastodon 4.2.8, but I think it's most helpful to provide the current release version as an indicator to readers.
=> Mastodon 4.2.8 (fetched on 2024-04-26)

docsets/PyQGIS/README.md, docsets/PyQGIS/docset.json, docsets/PyQGIS/pyqgis.patch, docsets/QGIS/README.md, docsets/QGIS/docset.json
Updating QGIS and PyQGIS docsets to version 3.38.1
Here are the links for the 2 docsets:
[QGIS docset](https://transfert.facil.services/r/9JXJ_6T6Gk#k9gUH/jSSrqUeHExTXnIMe5DUtt+0ETU0z9U9D0fKIk=)
[PyQGIS docset](https://github.com/user-attachments/files/16498579/PyQGIS_3.docset.zip)
Thanks 😉
=> Update QGIS and PyQGIS to 3.38.1

docsets/Blender/docset.json
Update Blender to latest LTS 4.2
The Blender.tgz is too large to push to Github, and is located in: https://www.dropbox.com/s/7mtqcgvznuy3lsw/Blender.tgz?dl=0
=> update Blender to 4.2

docsets/PEPs/README.md, docsets/PEPs/docset.json
No changelog since the PEPs repository doesn't have one.
=> PEPs.docset 2024.08.30

docsets/pytest/README.md, docsets/pytest/docset.json
upstream changelog: https://github.com/pytest-dev/pytest/compare/7.3.0...8.3.2
=> pytest.docset 8.3.2

docsets/RFCs/README.md, docsets/RFCs/docset.json
The docset file: [RFCs.tgz](https://files.pointless.one/RFCs-docset/2024.09.19-1.0.0/RFCs.tgz).
=> Update RFCs docset

docsets/Mastodon/Mastodon.tgz.txt, docsets/Mastodon/docset.json
Based on https://github.com/mastodon/documentation/commit/0b15ac190f6bbe6919f06e24be6f1fc80bb09c3d
The documentation doesn't specifically say Mastodon 4.3.0, but I think it's most helpful to provide the current release version as an indicator to readers.
=> Mastodon 4.3.0 (fetched on 2024-10-17)

docsets/Boto3/README.md, docsets/Boto3/boto3.tgz.txt, docsets/Boto3/docset.json
Binary available at https://d24v0t7zqzj9pw.cloudfront.net/1.35.49/boto3.tgz for 90d.
Thanks!
=> Bump boto3 to 1.35.49

docsets/xarray/README.md, docsets/xarray/docset.json, docsets/xarray/parser.py
Xarray docset was quite out of date, I took the liberty of updating it. I can continue to maintain it.
I included a custom doc2dash parser that filters out the (thousands of) duplicate entries, since every document and object has one or more "std:label"/section pointing to the same place.
=> Update Xarray to 2025.06.1
